# -*- coding: utf-8 -*-
"""Dialect Map

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7IhxmIrylcexs_af7i1QU5ur_0BdgAF
"""

import torch
import torch.nn as nn
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import csv
import geopandas as gpd
import folium
from IPython.display import display

m=folium.Map([48.6616,9.3501])
folium.Marker(location=[48.6616,9.3501],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Baden-Württemberg",
               popup="Dialect: Alemanisch").add_to(m)

folium.Marker(location=[ 47.6245,10.3146],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Allgäu",
              popup="Dialect: Allgäuerisch").add_to(m)

folium.Marker(location=[ 48.7904,11.4979],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Bavaria",
              popup="Dialect: Bairisch").add_to(m)

folium.Marker(location=[  52.5200,13.4050],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Berlin",
              popup="Dialect: Berlinerisch").add_to(m)

folium.Marker(location=[  49.7747,10.3556],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Franconia",
              popup="Dialect: Fränkisch").add_to(m)

folium.Marker(location=[  53.5511,9.9937],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Hamburg",
              popup="Dialect: Hamburgerisch").add_to(m)

folium.Marker(location=[   50.7753,8.9339],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Hesse",
              popup="Dialect: Hessisch").add_to(m)

folium.Marker(location=[50.9375,6.9603],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Köln",
              popup="Dialect: Kölsch").add_to(m)

folium.Marker(location=[53.6127,12.4296],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Mecklenburg",
              popup="Dialect: Mecklenburgisch").add_to(m)

folium.Marker(location=[ 51.1409,6.7601],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Lower Rhine",
              popup="Dialect: Niederrheinisch").add_to(m)

folium.Marker(location=[ 53.5531,7.3250],
              icon=folium.Icon(color="blue"),
              tooltip="Region: East Frisia",
              popup="Dialect: Ostfriesisch").add_to(m)

folium.Marker(location=[ 49.3110,8.4355],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Pfalz",
              popup="Dialect: Pfälzisch").add_to(m)

folium.Marker(location=[ 49.3964,6.9817],
              icon=folium.Icon(color="blue"),
              tooltip="Region: saarland",
              popup="Dialect: Saarländisch").add_to(m)

folium.Marker(location=[ 51.1045,13.2017],
              icon=folium.Icon(color="blue"),
              tooltip="Region: saxony",
              popup="Dialect: Sächsisch").add_to(m)

folium.Marker(location=[53.1632,7.6936],
              icon=folium.Icon(color="blue"),
              tooltip="Region: saterland",
              popup="Dialect: Saterfriesisch").add_to(m)

folium.Marker(location=[48.6299, 10.3325],
              icon=folium.Icon(color="blue"),
              tooltip="Region: schwaben",
              popup="Dialect: Schwäbisch").add_to(m)

folium.Marker(location=[51.0109, 10.8453],
              icon=folium.Icon(color="blue"),
              tooltip="Region: thuringia",
              popup="Dialect: Thüringisch").add_to(m)

folium.Marker(location=[51.5136,7.4653],
              icon=folium.Icon(color="blue"),
              tooltip="Region: westphalia",
              popup="Dialect: Westfälisch").add_to(m)

folium.Marker(location=[49.7500,6.1667],
              icon=folium.Icon(color="blue"),
              tooltip="Moselle").add_to(m)

folium.Marker(location=[51.4575,7.0140],
              icon=folium.Icon(color="blue"),
              tooltip="Region: Ruhrgebiet",
              popup="Dialect: Ruhrpottsprache").add_to(m)

display(m)

m.save("my_map.html")